version: "3.9"
services:
  backend:
    build: ./backend
    command: rails server -b 0.0.0.0 -p 3002
    volumes:
      - ./backend:/backend
      - ./backend/.env:/backend/.env
    ports:
      - "3002:3002"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/backend_development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=backend_development
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
