development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  firebase_project_id: shotsharing-login
  firebase_web_api_key: AIzaSyDattVHvE7oqyM0A4-S99RWyVgO9khk9xo
  google_project_id: shotsharing-login
  google_api_key: AIzaSyBLq1f9vDX7y93bxgV2lmpfRdEo6f--OS0

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  firebase_project_id: <%= ENV["FIREBASE_PROJECT_ID"] %>
  firebase_web_api_key: <%= ENV["FIREBASE_WEB_API_KEY"] %>
