name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        working-directory: ./backend
        run: docker build . --platform linux/amd64 -t kaiwajun/shotsharing-backend:latest
      - uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "shotsharing-backend"
          heroku_email: "kj.11235813213455@gmail.com"
          usedocker: true
